[package]
name = "indexed_valued_enums"
version = "0.8.0"
edition = "2021"
authors = ["Jorge Rico Vivas <jorgericosoftware@gmail.com>"]

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0.193", optional=true }

[features]
serde_enums=["dep:serde"]