[package]
name = "indexed_valued_enums_derive"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.78", features = [] }
quote = { version ="1.0.35", features = [] }
syn = { version = "1.0.109", features = ["extra-traits"] }